version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  fetch-config:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Fetch configuration from infra repository
          command: |
            git clone -b migration-config https://github.com/babylonchain/babylon-service-infra.git
            cp babylon-service-infra/staking-expiry-checker/* .circleci/
      - continuation/continue:
          configuration_path: .circleci/circleci-config.yml

workflows:
  setup:
    jobs:
      - fetch-config
