namespace: staking-expiry-checker
name: staking-expiry-checker
deployment:
  image: 490721144737.dkr.ecr.us-east-1.amazonaws.com/staking-expiry-checker
  version: REPLACEME
  replicas: 2
  ports:
    - protocol: TCP
      containerPort: 2112
      name: prom
  env:
    - name: CONFIG
      value: /home/staking-expiry-checker/config.yml
  volumes:
    - name: staking-expiry-checker
      configMap:
        name: staking-expiry-checker
  volumeMounts:
    - name: staking-expiry-checker
      subPath: config.yml
      mountPath: /home/staking-expiry-checker/config.yml
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "2112"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    configmap.reloader.stakater.com/reload: "staking-expiry-checker"
  nodeSelector:
    workload: "webservices"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app: staking-expiry-checker
            topologyKey: topology.kubernetes.io/zone
          weight: 1
service:
  type: NodePort
  ports:
    - protocol: TCP
      port: 2112
      targetPort: prom
      name: prom
ingress:
  enabled: true
  groupName: "mainnet-internal"
  tlsCertArn: arn:aws:acm:us-east-2:490721144737:certificate/2c6cb5ad-8899-4871-9206-ea8e978aebae
  scheme: "internal"
  hosts:
    - host: staking-expiry-checker.mainnet.babylonchain.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: staking-expiry-checker
#                port:
#                  name: staking-expiry-checker
externalDns:
  fqdn: staking-expiry-checker.mainnet.babylonchain.io
  ttl: 60
purgeCloudflareCache:
  enabled: false
configFiles:
  config.yml: |    
    poller:
      interval: 5s
      log-level: debug
    db:
      address: mongodb://mongodb-headless.mongodb-staking-api:27017
      db-name: staking-api-service
    btc:
      endpoint: localhost:18332 # use port 18332 for testnet, 8332 for mainnet
      disable-tls: false
      net-params: testnet
      rpc-user: rpcuser
      rpc-pass: rpcpass
    queue:
      queue_user: USER
      queue_password: PASSWORD
      url: "rabbitmq-headless.rabbitmq:5672"
      processing_timeout: 5 # 5 second
    metrics:
      host: 0.0.0.0
      port: 2112
