poller:
  interval: 5s
  log-level: debug
db:
  address: "mongodb://mongodb:27017"
  db-name: staking-api-service
btc:
  endpoint: localhost:18332 # use port 18332 for testnet, 8332 for mainnet
  disable-tls: false
  net-params: testnet
  rpc-user: rpcuser
  rpc-pass: rpcpass
queue:
  user: guest # can be replaced by values in .env file
  pass: guest
  url: "rabbitmq:5672"
  processing_timeout: 5 # 5 second
metrics:
  host: 0.0.0.0
  port: 2112