name: ci

on:
  pull_request:
    branches:
    - '**'

jobs:
  lint_test:
    uses: babylonchain/.github/.github/workflows/reusable_go_lint_test.yml@hiep/add-reusable-workflows
    with:
     run-unit-tests: true
     run-integration-tests: false
     run-lint: true
     
  docker_pipeline:
    uses: babylonchain/.github/.github/workflows/reusable_docker_pipeline.yml@hiep/add-reusable-workflows
    secrets: inherit
    with:
      publish: false
      dockerfile: ./contrib/images/staking-expiry-checker/Dockerfile
      dockerfile: ./contrib/images/staking-expiry-checker/Dockerfile