name: docker_publish

on:
  push:
    branches:
    - 'main'
    - 'dev'
    tags:
    - '*'

jobs:
  lint_test:
    uses: babylonchain/.github/.github/workflows/reusable_go_lint_test.yml@hiep/add-reusable-workflows
    with:
      run-unit-tests: true
      run-integration-tests: false
      run-lint: true
     
  docker_pipeline:
    needs: ["lint_test"]
    uses: babylonchain/.github/.github/workflows/reusable_docker_pipeline.yml@hiep/add-reusable-workflows
    secrets: inherit
    with:
     publish: true
     dockerfile: ./contrib/images/staking-expiry-checker/Dockerfile